server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/VeggieFood?useUnicode=true&characterEncoding=UTF-8
    password: 9113
    username: root
    driverClassName: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        id: new_generator_mappings=true
  mail: # Sửa: đặt trực tiếp dưới "spring"
    host: smtp.gmail.com
    port: 587
    username: loin01012004@gmail.com
    password: your-app-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  signerKey: "CP9r4sIu58bPpUhyXeYzSfP+i7H3AMIU8YUTLHaR8oVPLQHcj9iGO+RQf2nmWeNt"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds

# Cấu hình Camunda
camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
    rest:
      enabled: true
      engine-name: default
    filter:
      create: All tasks
    history-level: full
    run:
      cors:
        enabled: true
        allowed-origins: "localhost:3000"
        allowed-methods: "GET, POST, PUT, DELETE"
    # webapp:
    #   security:
    #     enabled: true
    #     provider: keycloak

    # url: http://localhost:8899/engine-rest
    # identity:
    #   keycloak:
    #     enabled: true
    #     server-url: http://localhost:8081/realms/spin-wheel
    #     client-id: spinpj-rest-api
    #     use-username-as-principal: true
    # database:
    #   schema-update: true # Tự động cập nhật schema khi khởi động
    deployment-resource-pattern: classpath*:processes/*.bpmn
logging:
  level:
    org.camunda: DEBUG
    org.springframework.web: DEBUG


# Cấu hình JWT



vnpay:
  tmnCode: "WQLVBKW6"
  hashSecret: "013XTWHQVJC9R5JQY20U3C9V14CEVSRI"
  url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
  returnUrl: "http://localhost:8080/payment/return"
  apiUrl: "https://sandbox.vnpayment.vn/merchant_webapi/api/transaction"
  version: "2.1.0"
  currency: "VND"