server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/VeggieFood?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    password: ${DBMS_PASSWORD:9113}
    username: ${DBMS_USERNAME:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail: # Sửa: đặt trực tiếp dưới "spring"
    host: smtp.gmail.com
    port: 587
    username: loin01012004@gmail.com
    password: your-app-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  signerKey: "CP9r4sIu58bPpUhyXeYzSfP+i7H3AMIU8YUTLHaR8oVPLQHcj9iGO+RQf2nmWeNt"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds

# Cấu hình Camunda
camunda:
  bpm:
    auto-deployment-enabled: true
    admin-user:
      id: admin
      password: admin
    filter:
      create: All tasks
    database:
      schema-update: true

# Cấu hình JWT



vnpay:
  tmnCode: "WQLVBKW6"
  hashSecret: "013XTWHQVJC9R5JQY20U3C9V14CEVSRI"
  url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
  returnUrl: "http://localhost:8080/payment/return"
  apiUrl: "https://sandbox.vnpayment.vn/merchant_webapi/api/transaction"
  version: "2.1.0"
  currency: "VND"